#!/usr/bin/env python3
"""Generate the SAF detection coverage matrix from canonical registries."""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from pathlib import Path

import yaml


def load(path: Path) -> dict:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a mapping")
    return value


def build(root: Path) -> str:
    model = load(root / "research/framework-model.yml")
    registry = load(root / "detections/registry.yml")
    external = load(root / "detections/external-mappings.yml")
    providers = [load(path) for path in sorted((root / "detections/providers").glob("*.yml"))]

    active = [item for item in model["techniques"] if item["lifecycle_status"] == "active"]
    default_relationship = registry["native_mapping"]["default_relationship"]
    validated_by_technique: dict[str, list[dict]] = defaultdict(list)
    for mapping in external["mappings"]:
        if mapping["status"] == "validated":
            validated_by_technique[mapping["technique_id"]].append(mapping)

    relationship_counts: Counter[str] = Counter()
    modality_counts: Counter[str] = Counter()
    for item in active:
        mapping = registry["techniques"][item["technique_id"]]
        relationship_counts[mapping.get("relationship", default_relationship)] += 1
        modality_counts.update(mapping["modalities"])
    unrepresented = [
        modality for modality in registry_ordered_modalities() if not modality_counts[modality]
    ]

    lines = [
        "# SAF Detection Coverage",
        "",
        "> Generated by `scripts/generate-detection-coverage.py`. Edit the source registries, not this file.",
        "",
        "This matrix links active SAF techniques to their native analytics and normalized observation modalities. "
        "It records mapping and validation state; it does not measure production detection effectiveness or guarantee complete coverage. "
        "See the [registry policy](README.md) for semantics and ownership boundaries.",
        "",
        "## Summary",
        "",
        f"- Active techniques with a native analytic: **{len(active)} of {len(active)}**",
        f"- Native mapping relationships: **{relationship_counts['direct']} direct**, "
        f"**{relationship_counts['partial']} partial**, **{relationship_counts['adjacent']} adjacent**",
        f"- Validated external mappings: **{sum(len(value) for value in validated_by_technique.values())}**",
        "- Unrepresented native observation modalities: "
        + (", ".join(f"**`{value}`**" for value in unrepresented) if unrepresented else "**none**"),
        "",
        "## Observation modalities",
        "",
        "A mapping may represent more than one modality, so these counts overlap.",
        "",
        "| Modality | Active native mappings |",
        "| --- | ---: |",
    ]
    for modality in registry_ordered_modalities():
        lines.append(f"| `{modality}` | {modality_counts[modality]} |")

    lines.extend(
        [
            "",
            "## Active technique matrix",
            "",
            "| Technique | Native analytic | Relationship | Validation | Modalities | Validated external rules |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for item in active:
        technique_id = item["technique_id"]
        mapping = registry["techniques"][technique_id]
        relationship = mapping.get("relationship", default_relationship)
        detection = item["detection"]
        technique_link = f"[{technique_id}](../{item['technique_path']}) — {item['name']}"
        rule_link = f"[rule](../{detection['rule']})"
        modalities = ", ".join(f"`{value}`" for value in mapping["modalities"])
        external_rules = []
        for external_mapping in validated_by_technique[technique_id]:
            external_rules.append(
                f"[{external_mapping['provider_id']}:{external_mapping['rule_id']}]"
                f"({external_mapping['rule_url']}) "
                f"([evidence]({external_mapping['evidence_url']}), "
                f"`{external_mapping['relationship']}`)"
            )
        lines.append(
            f"| {technique_link} | {rule_link} | `{relationship}` | "
            f"`{detection['validation_level']}` | {modalities} | "
            f"{'<br>'.join(external_rules) if external_rules else '—'} |"
        )

    lines.extend(
        [
            "",
            "## External provider intake",
            "",
            "Provider sources under reconciliation remain visible here but do not count as validated external mappings.",
            "",
            "| Provider | Repository | Candidate mapping | Intake status | Reviewed |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    if not providers:
        lines.append("| — | — | — | — | — |")
    for provider in providers:
        source = provider.get("candidate_source") or {}
        repository = f"[repository]({provider['repository']})"
        mapping_url = source.get("mapping_url")
        mapping_link = f"[source]({mapping_url})" if mapping_url else "—"
        lines.append(
            f"| {provider['name']} | {repository} | {mapping_link} | "
            f"`{source.get('status', '—')}` | {source.get('reviewed_on', '—')} |"
        )
    lines.append("")
    return "\n".join(lines)


def registry_ordered_modalities() -> list[str]:
    return [
        "content",
        "static",
        "runtime",
        "gateway",
        "endpoint",
        "identity",
        "network",
        "memory",
        "multimodal",
        "model-lifecycle",
        "on-chain",
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    output_path = root / "detections/COVERAGE.md"
    generated = build(root)
    if args.check:
        if not output_path.is_file() or output_path.read_text(encoding="utf-8") != generated:
            raise SystemExit(
                "detection coverage matrix is stale; run scripts/generate-detection-coverage.py"
            )
        print("PASS: detection coverage matrix is current")
        return 0
    output_path.write_text(generated, encoding="utf-8")
    print("Updated detections/COVERAGE.md from canonical registries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
